ok: Reine Pbm
Reine: L.java Search.java Backtrack.java Reine.java
	javac L.java Search.java Backtrack.java Reine.java 
	java Reine 8
Pbm: L.java Search.java Backtrack.java Pbm.java
	javac L.java Search.java Backtrack.java Pbm.java
	java Pbm
